// File generated by FlutterFire CLI — replace with your project via:
//   dart pub global activate flutterfire_cli && flutterfire configure
//
// Placeholder values allow the project to compile; replace before production.

import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import "package:flutter/foundation.dart"
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc2PeAqKnVOzyJtz6hz3mJIfkM5xAJKM4',
    appId: '1:39514107844:web:a91b07b104783b6d0afe91',
    messagingSenderId: '39514107844',
    projectId: 'walklingo',
    authDomain: 'walklingo.firebaseapp.com',
    storageBucket: 'walklingo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMF3R0BHm4X14YI2j8SyBeowrRfHs_wek',
    appId: '1:39514107844:android:5de669d99d3ece6c0afe91',
    messagingSenderId: '39514107844',
    projectId: 'walklingo',
    storageBucket: 'walklingo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4knzXBnjTYLGShhxZI2UIdvAp0w3fMFM',
    appId: '1:39514107844:ios:8f6a1b906eface7d0afe91',
    messagingSenderId: '39514107844',
    projectId: 'walklingo',
    storageBucket: 'walklingo.firebasestorage.app',
    iosBundleId: 'vn.walklingo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4knzXBnjTYLGShhxZI2UIdvAp0w3fMFM',
    appId: '1:39514107844:ios:8f6a1b906eface7d0afe91',
    messagingSenderId: '39514107844',
    projectId: 'walklingo',
    storageBucket: 'walklingo.firebasestorage.app',
    iosBundleId: 'vn.walklingo.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc2PeAqKnVOzyJtz6hz3mJIfkM5xAJKM4',
    appId: '1:39514107844:web:d755e7a707cbf2b70afe91',
    messagingSenderId: '39514107844',
    projectId: 'walklingo',
    authDomain: 'walklingo.firebaseapp.com',
    storageBucket: 'walklingo.firebasestorage.app',
  );
}
